# Generated by Django 5.0.6 on 2024-06-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=252, verbose_name='Титуд')),
                ('description', models.TextField(verbose_name='Описание')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('status', models.CharField(choices=[('cr', 'Создана'), ('in', 'В прогрессе'), ('dn', 'Сделан'), ('cn', 'Отклонен'), ('ex', 'Просрочен')], max_length=2, verbose_name='Статус')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_ad', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
